### ISSUE TITLE
Feature request: update a subscription

### ISSUE THREAD

**Issue by TAnas0** [avaly/paddle-sdk#10]
Hello,

From your documentation, it seems that the [Update Subscription](https://developer.paddle.com/api-reference/subscription-api/subscription-users/updateuser) functionality of Paddle's API is not implemented.

Asking here in case it is implemented, just not documented.

If for some reason you can not implement it, let me know and I'll make a merge request for it.

Cheers

**Comment by avaly** [comment]
It's not implemented. Please submit a PR.

**Comment by TAnas0** [comment]
@avaly I have made a small implementation for `updateSubscriptionPlan`, but I have problem testing though.

More precisely, I am having problems with the Nock package. Please run the tests on my repository (https://github.com/TAnas0/paddle-sdk/tree/master) so you can see the error and let me know.

On another subject, the `updateSubscriptionPlan` does very minimal job. All it does is make a request, so I don't think that tests on it bring much of value. Same goes for many other methods.

Anyway, I can't manage to mock the requests to the new Paddle endpoint and I can't figure out why. Maybe you could help me in that.

**Comment by avaly** [comment]
Implemented in https://github.com/avaly/paddle-sdk/commit/310f54d932b3d4f6715c9ee668cdc6c43523ce4b
