### ISSUE TITLE
fix annoy build warnings in vue project with webpack

### ISSUE THREAD

**Issue by nonew** [avaly/paddle-sdk#11]
I think you should upgrade dependencies 'got' and 'keyv' to latest one.

WARNING in ../node_modules/paddle-sdk/node_modules/got/source/request-as-event-emitter.js 72:18-25
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../node_modules/paddle-sdk/node_modules/got/source/as-stream.js
 @ ../node_modules/paddle-sdk/node_modules/got/source/create.js
 @ ../node_modules/paddle-sdk/node_modules/got/source/index.js
 @ ../node_modules/paddle-sdk/sdk.js
 @ ../node_modules/babel-loader/lib!../node_modules/vue-loader/lib??vue-loader-options!./components/PopupPage.vue?vue&type=script&lang=js&
 @ ./components/PopupPage.vue?vue&type=script&lang=js&
 @ ./components/PopupPage.vue
 @ ./popup.js

WARNING in ../node_modules/keyv/src/index.js 18:14-40
Critical dependency: the request of a dependency is an expression
 @ ../node_modules/paddle-sdk/node_modules/cacheable-request/src/index.js
 @ ../node_modules/paddle-sdk/node_modules/got/source/request-as-event-emitter.js
 @ ../node_modules/paddle-sdk/node_modules/got/source/as-stream.js
 @ ../node_modules/paddle-sdk/node_modules/got/source/create.js
 @ ../node_modules/paddle-sdk/node_modules/got/source/index.js
 @ ../node_modules/paddle-sdk/sdk.js
 @ ../node_modules/babel-loader/lib!../node_modules/vue-loader/lib??vue-loader-options!./components/PopupPage.vue?vue&type=script&lang=js&
 @ ./components/PopupPage.vue?vue&type=script&lang=js&
 @ ./components/PopupPage.vue
 @ ./popup.js

**Comment by avaly** [comment]
Upgraded latest deps in v2.0.0
