### ISSUE TITLE
Is support for CommonJS dropped since v4?

### ISSUE THREAD

**Issue by ivstiv** [avaly/paddle-sdk#71]
I just upgraded to the latest version and got this error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /app/node_modules/.pnpm/paddle-sdk@4.0.0/node_modules/paddle-sdk/esm/sdk.js from /app/dist/utilities/paddle.js not supported.
```
I am not asking for a fix, just checking what the intention of the major upgrade is, since the change log doesn't acknowledge dropping of CJS support.

**Comment by avaly** [comment]
It's definitely not intentional. I'll fix this bug and deploy a fix version later today.
